### ISSUE TITLE
Honeypot fields not closing tags correctly

### ISSUE THREAD

**Issue by adambichler** [erikyo/cf7-antispam#12]
When form fields are wrapper in divs, the honeypot fields will somehow interrupt closing the div.

This is how the form looks without the plugin activated (how it schould be)
![honeypots not activated](https://user-images.githubusercontent.com/44649310/196967545-77fdca0d-b821-44e6-bab9-2bddf68328af.png)

And if the plugin is activated, it looks like this
![honeypots activated](https://user-images.githubusercontent.com/44649310/196967535-57d3a0fe-f24e-4493-ab89-271f635a249f.png)
This is interfering with the design, as the columns are not rendered correctly (field columns are inside the first field column)

This is the form code:
```
<div class="field-column">
[text* fullname placeholder "Vorname Nachname*"]
</div>
<div class="field-column">
[text* phone class:phone placeholder "Telefon* +43 …"]
</div>
<div class="field-column">
[email* email placeholder "E-Mail*"]
</div>
<div class="field-column align-right last">
[acceptance policy] Ich habe die <a href="/datenschutz" target="_blank">Datenschutzbestimmungen</a> gelesen und stimme ihnen zu. [/acceptance]
[submit "absenden"]
</div>
```
 Thanks for the [last patch](https://github.com/erikyo/cf7-antispam/issues/10), its working!

**Comment by erikyo** [comment]
thanks @adambichler for bringing this to my attention (and providing me with a test case to try out)! A user had pointed it out to me on the wordpress forum I think I solved it some days ago, here https://github.com/erikyo/cf7-antispam/commit/0e3fa8637727491b32e3099004df116a4d669e9b

![image](https://user-images.githubusercontent.com/8550908/196975521-e1ac91b7-76f3-4366-a7a0-9e111ff0fe9b.png)

In the 0.4 version (apart the geoip module) I tried to stabilise the plugin filters so that they would not have this kind of issues...  I am currently running tests with a few different devices to check that everything is working as it should. 

I am keeping this issue open until you try the new version and confirm that it works properly.

**Comment by erikyo** [comment]
@adambichler I'm doing a bit of testing by installing the plugin on a bunch of my websites to see if it generates any errors then if you're interested I'll release a beta here on GitHub so you can try out the next version.

Alternatively you can download the repo version but you have to fire `composer install` inside the plugin folder to install the geo-ip dependencies

**Comment by adambichler** [comment]
Hello @erikyo 
thanks for your quick response. I tried downloading the GitHub Version and installed the dependencies, but it gave me an error for a missing class "CF7_AntiSpam_Admin_Tools" when trying to activate the plugin. As I am a bit in a hurry right now, I don't have time to look into it at the moment, but I will check it out as soon as the wordpress version is released.

**Comment by erikyo** [comment]
close by automations... reopen

**Comment by erikyo** [comment]
Ciao @adambichler I think we are close to release, if you want to give it a try, I hope we can set aside the issue with honeypots because I have reworked that function (btw, there is a freshly published beta [here](https://github.com/erikyo/cf7-antispam/releases/tag/beta)). 

Unfortunately, no matter how many tests I do, they are never enough so any feedback from other users is always appreciated!

**Comment by adambichler** [comment]
Hello @erikyo 
Thank you! I can confirm that the divs are now closing correctly. However I encountered a plugin conflict that was not there in version 0.3.0.

When the plugin "Email Encoder - Protect Email Addresses" (https://de.wordpress.org/plugins/email-encoder-bundle/) is active, the page will only render until the form is embedded, not further. So if there would be page content below the form, for example the page footer, the footer will be completely missing.

If you need further help in reproducing the error, feel free to contact me.

Best regards, Adam

**Comment by erikyo** [comment]
sorry @adambichler I forgot to update you on this but I think I've solved the incompatibility problem with the plugin you were reporting... by chance we were using the same filter (but in the wrong sequence), mine had to be set after 'Email Encoder' as I have to act on the 'final' fields of the form. thank you again!

**Comment by erikyo** [comment]
it seems that with the latest update of contact form 7 (5.7) the function that generates the html has been improved and should no longer generate invalid code. 

In any case if anyone still has problems, please reopen this issue!
