### ISSUE TITLE
"internal_server_error" when submitting form with empty message

### ISSUE THREAD

**Issue by MeliEve** [erikyo/cf7-antispam#41]
Hi Erik, thanks for your hard work in this plugin. I have found an issue.
If you have Flamingo installed alongside this plugin, and you submit a form without a message, an error 500 will rise.
The error is produced in line 338 of file `includes/cf7a-antispam-flamingo.php`, and it happens because a string parameter ('none') is being passed to round().
It's an easy fix.

**Comment by MeliEve** [comment]
@erikyo Sorry I don't know where to approve the review. Tbh I can't find the review you are talking about 😅 
Also, I think the PR I made works for when it is a numerical value and when it is not, don't you think?
Thank you!

**Comment by erikyo** [comment]
Thanks to you! Always good to see participation to improve the plugin! 

> **I can't find the review**

should be [here](https://github.com/erikyo/cf7-antispam/pull/42/files) and you should see a green button under my suggestion (I cannot approve my suggestions, and in this way you get the code contribution correctly). Basically my addition says that if it is a number it can be rounded, while in all other cases it is stored as is

screenshot 👇
![image](https://user-images.githubusercontent.com/8550908/232759625-0dbc91cc-04af-4821-952c-7f91cabe5874.png)

---

> **I think the PR I made works for when it is a numerical value and when it is not, don't you think?**

Yes indeed it works and it is super-correct! My addition was to get the stored value a little more readable since the b8 rating looks like 0.8456413546 but we only need to display 0.84, Is just a cosmetic change/simplification. 

![image](https://user-images.githubusercontent.com/8550908/232761320-362192a6-e529-4c46-8edf-ae641d18836b.png)

1 - without round values
2 - with values rounded
